name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install --with-deps

    - name: Show environment info (debug)
      run: |
        python --version
        pip --version
        pip list --format=columns

    - name: Run tests and generate HTML report
      env:
        CI: true
        HEADLESS: true
      run: |
        mkdir -p report
        pytest -vv --maxfail=1 --html=report/report.html --self-contained-html --capture=tee-sys

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report/report.html

  
